#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
pushd "$SCRIPT_DIR" || exit 1

if command -v gtar >/dev/null; then
  gtar cvf ../applescript-embed.tar ./*
elif tar --version | grep -q bsdtar; then
  echo "[!] archive must be generated by GNU tar; found bsdtar"
  echo "[!] if gtar is found in the path, it will be used"
  echo "[!] on macOS, run 'brew install gnu-tar'"
  exit 1
else
  tar cvf ../applescript-embed.tar ./*
fi
